export const FETCH_POKEMON_LIST_REQUEST = "FETCH_POKEMON_LIST_REQUEST";
export const FETCH_POKEMON_LIST_SUCCESS = "FETCH_POKEMON_LIST_SUCCESS";
export const FETCH_POKEMON_LIST_FAILURE = "FETCH_POKEMON_LIST_FAILURE";

export const SET_SEARCH_FILTER = "SET_SEARCH_FILTER";
export const SET_TYPE_FILTER = "SET_TYPE_FILTER";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const LOAD_FAVORITES = "LOAD_FAVORITES";
